# Generated by Django 6.0.3 on 2026-04-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_categor_6be84d_idx',
            old_name='core_listin_categor_c80164_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_city_to_6ad9bb_idx',
            old_name='core_listin_city_to_17f18b_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_gender_6dd3f0_idx',
            old_name='core_listin_gender_e2f83d_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_status_d19315_idx',
            old_name='core_listin_status_7d1160_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_last_ve_7ed0a3_idx',
            old_name='core_listin_last_ve_f1f9af_idx',
        ),
    ]
