# Generated by Django 6.0.3 on 2026-04-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_dates'),
        ('core', '0002_rename_core_listin_categor_c80164_idx_core_listin_categor_6be84d_idx_and_more'),
    ]

    operations = [
    ]
