# Generated by Django 6.0.3 on 2026-04-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260406_1247'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_start_d_a8d9b6_idx',
            old_name='core_listin_start_d_00df4d_idx',
        ),
    ]
