# Generated by Django 6.0.3 on 2026-04-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitytype_citytown_county_sporttype_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingOutdatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdated_reports', to='core.listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_listin_created_89f226_idx'), models.Index(fields=['resolved'], name='core_listin_resolve_b32dca_idx')],
            },
        ),
    ]
