# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations


SPORT_TYPES = [
    'Archery',
    'Badminton',
    'Baseball',
    'Basketball',
    'BMX',
    'Bowling',
    'Boxing',
    'Cheerleading',
    'Cricket',
    'Cross Country',
    'Cycling',
    'Disc Golf',
    'Diving',
    'Equestrian',
    'Fencing',
    'Figure Skating',
    'Flag Football',
    'Football',
    'Golf',
    'Gymnastics',
    'Handball',
    'Ice Hockey',
    'Inline Skating',
    'Judo',
    'Karate',
    'Kayaking',
    'Lacrosse',
    'Martial Arts',
    'Mountain Biking',
    'Pickleball',
    'Racquetball',
    'Rock Climbing',
    'Roller Hockey',
    'Rowing',
    'Rugby',
    'Sailing',
    'Skateboarding',
    'Skiing',
    'Snowboarding',
    'Soccer',
    'Softball',
    'Speed Skating',
    'Squash',
    'Surfing',
    'Swimming',
    'Table Tennis',
    'Taekwondo',
    'Tennis',
    'Track and Field',
    'Triathlon',
    'Ultimate Frisbee',
    'Volleyball',
    'Water Polo',
    'Weightlifting',
    'Wrestling',
]


def seed_sport_types(apps, schema_editor):
    SportType = apps.get_model('core', 'SportType')
    for name in SPORT_TYPES:
        SportType.objects.get_or_create(name=name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_listingoutdatedreport'),
    ]

    operations = [
        migrations.RunPython(seed_sport_types, reverse_code=noop_reverse),
    ]
