# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations


ACTIVITY_TYPES = [
    'After School Program',
    'Art Classes',
    'Band / Instrumental',
    'Book Club',
    'Chess Club',
    'Choir / Vocal',
    'Coding / Programming',
    'Cooking / Baking',
    'Creative Writing',
    'Dance',
    'Debate / Public Speaking',
    'ESL / Language Support',
    'Film / Video',
    'Fitness / Conditioning',
    'Gardening',
    'Hiking / Nature Club',
    'Homeschool Co-op Activities',
    'Language Classes',
    'Leadership Programs',
    'Martial Arts (Non-Competitive)',
    'Math Enrichment',
    'Music Lessons',
    'Outdoor Adventure',
    'Photography',
    'Religious / Faith-Based Youth Group',
    'Robotics',
    'STEM Clubs',
    'Science Clubs',
    'Scouting',
    'Special Needs Programs',
    'Summer Camp',
    'Theater / Drama',
    'Tutoring / Homework Help',
    'Vacation Camp',
    'Volunteer / Community Service',
    'Yoga / Mindfulness',
    'Fishing',
]


def seed_activity_types(apps, schema_editor):
    ActivityType = apps.get_model('core', 'ActivityType')
    for name in ACTIVITY_TYPES:
        ActivityType.objects.get_or_create(name=name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_seed_sport_types'),
    ]

    operations = [
        migrations.RunPython(seed_activity_types, reverse_code=noop_reverse),
    ]
