# Generated by Django 6.0.3 on 2026-04-07 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_ma_counties_and_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to='listing_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])]),
        ),
    ]
