# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations


def migrate_legacy_statuses(apps, schema_editor):
    Listing = apps.get_model('core', 'Listing')
    Listing.objects.filter(status='active').update(status='published')
    Listing.objects.filter(status='inactive').update(status='archived')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_alter_listing_status'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_statuses, reverse_code=noop_reverse),
    ]
