# Generated by Django 6.0.3 on 2026-04-07 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listing_created_by_listing_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('activity', 'Activity')], max_length=20)),
                ('subtype', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=255)),
                ('city_town', models.CharField(max_length=120)),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('age_min', models.PositiveSmallIntegerField()),
                ('age_max', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Co-ed'), ('not_specified', 'Not specified')], default='not_specified', max_length=20)),
                ('season_or_dates', models.CharField(max_length=255)),
                ('registration_url', models.URLField()),
                ('image', models.FileField(blank=True, upload_to='listing_suggestions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])])),
                ('description', models.TextField()),
                ('submitter_name', models.CharField(blank=True, max_length=150)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='core.activitytype')),
                ('approved_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestions', to='core.listing')),
                ('city_town_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='core.citytown')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='core.county')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('sport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='core.sporttype')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='core.state')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_listin_status_264ba0_idx'), models.Index(fields=['created_at'], name='core_listin_created_795309_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('age_max__gte', models.F('age_min'))), name='suggestion_age_max_gte_age_min')],
            },
        ),
    ]
