# Generated by Django 6.0.3 on 2026-04-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_listing_perf_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_subtype_ee93bb_idx',
            old_name='core_listing_subtype_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_status_54e329_idx',
            old_name='core_listing_status_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_status_fa67a7_idx',
            old_name='core_listing_status_start_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='core_listin_status_6e34d0_idx',
            old_name='core_listing_status_cat_sub_city_idx',
        ),
    ]
