# Generated by Django 6.0.3 on 2026-04-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_listinganalyticsevent'),
        ('core', '0017_rename_core_listing_subtype_idx_core_listin_subtype_ee93bb_idx_and_more'),
    ]

    operations = [
    ]
