# Generated by Django 6.0.3 on 2026-04-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260407_1513'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listinganalyticsevent',
            new_name='core_listin_event_t_4852eb_idx',
            old_name='core_listin_event_t_11f5d6_idx',
        ),
        migrations.RenameIndex(
            model_name='listinganalyticsevent',
            new_name='core_listin_query_99b778_idx',
            old_name='core_listin_query_435b11_idx',
        ),
        migrations.RenameIndex(
            model_name='listinganalyticsevent',
            new_name='core_listin_section_47897c_idx',
            old_name='core_listin_section_2c7fe3_idx',
        ),
    ]
